services:
  # --- Backend (Node runtime) ---
  - type: web
    name: madetoheal-backend
    runtime: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: madetoheal-db         # this name must match your DB name in Render
          property: connectionString
      - key: JWT_SECRET
        sync: false

  # --- Frontend (Node runtime) ---
  - type: web
    name: madetoheal-frontend
    runtime: node
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_API_URL
        sync: false

databases:
  - name: madetoheal-db
    plan: basic-1gb
