services:
  - type: web
    name: madetoheal-backend
    runtime: docker
    plan: starter
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: madetoheal-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

  - type: web
    name: madetoheal-frontend
    runtime: docker
    plan: starter
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        sync: false

databases:
  - name: madetoheal-db
    # pick ONE of these current plans:
    # plan: free          # great to start, 1 GB disk by default
    plan: basic-1gb       # small paid, 15 GB disk by default
    # Optional: explicitly set disk size (1 or multiples of 5)
    # diskSizeGB: 15
