# Render services: backend + frontend + postgres
services:
  - type: web
    name: madetoheal-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    instanceType: starter
    envVars:
      - key: DATABASE_URL
        scope: env
      - key: JWT_SECRET
        scope: env
  - type: web
    name: madetoheal-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    instanceType: starter
databases:
  - name: madetoheal-db
    plan: starter
